🚀 Github Actions Workflows
ttauri-project/ttauri pull request #110
Opened 2021-03-24 06:20 UTC by jakoch

This PR adds the following workflows: `Build On Windows`, `Build Documentation` and `CodeQL Analysis`.

- The `Build On Windows` workflow is a build matrix for Windows with triplet and PCH compile flag support.
   - Build Artifacts are uploaded per matrix run.
   - Test Artifacts are uploaded into a shared test artifact and then published by the job `publish-test-results` after the matrix finishes, so that tests statistics of all runs are aggregated and displayed.
- The `Build Documentation` workflow triggers the (re-)building of the documentation on the docs repo.
   - It uses the GithubToken to make the `workflow_dispatch` request.
   - I couldn't trigger/test this from a fork. I hope the permission level fits, when the request is made from the official repo.
- The `CodeQL Analyze` workflow builds the x64-windows-static triplet with CodeQL scanning enabled and uploads the scan report.
   - The config resides in `./.github/codeql/codeql-config.yml` and is using the `security-and-quality` scan.
   - Other scans are prepared, but commented out. The Config needs tweaking. 
   - Reports should appear under the "Security" tab.
- The `Build On Windows` and `CodeQL Analyze` depend on the job `install-vulkan-sdk-and-runtime`.
    - This is an independend job, because the cache is shared by all matrix runs.
    - The job resides in both files, because it's not supported on GHA (yet) to call jobs from other workflow files.
- `Build On Windows` depends on an external file `.vsconfig`, which contains the description of required Visual Studio Components. The file was exported from VSInstaller.

❗   **Expected failure** on the PCH:ON run. A pull request containing the header fixes will follow.

Known Issues of Github Actions i ran into: 
- Status badges for each run of the build matrix are not supported, yet 
- Running a dependend job from another workflow file doesn't work, yet
- Build artifact is zipped twice. Not fixed, yet.
- 🙄 

Please review and comment on the code, so that we can get it into a state, where it is ready to be merged.

2021-03-24 12:00 UTC, takev requested changes

2021-03-24 12:00 UTC, takev commented on .github/workflows/build-on-windows.yml
> +          - { VCPKG_TARGET_TRIPLET: x64-windows-static, BUILD_SHARED_LIBS: OFF, TT_BUILD_PCH: ON}
I changed ttauri so that BUILD_SHARED_LIBS is now automatically gets set by the VCPKG_TARGET_TRIPLET.

2021-03-24 12:00 UTC, takev commented on .github/workflows/build-on-windows.yml
> +          - { VCPKG_TARGET_TRIPLET: x64-windows-static, BUILD_SHARED_LIBS: OFF, TT_BUILD_PCH: ON}
I wonder for performance reasons if we should only build with TT_BUILD_PCH: OFF.
That way we do a proper source code test.
At least the OFF test should be done first, so we can only make that one "required" when merging.

2021-03-24 12:00 UTC, takev commented on .github/workflows/build-on-windows.yml
> +          cmake -G "Visual Studio 16 2019" -A ${{ env.PLATFORM }}                           ^
As with appveyor it seems artifacts must be relative to the source directory.
It is probably best (which is also what most install manuals would say when building with cmake) to create
a build directory inside the source directory. cd into the build and then do the same without the -B option and with .. as the last argument.

That way you can directly execute build and install from that same directory as well.

2021-03-24 12:00 UTC, takev commented on .github/workflows/build-on-windows.yml
> +        run: cmake --install ..\build --config %BUILD_TYPE% --prefix ..\install --strip --verbose
Install into a subdirectory of the build directory. Already using a variable to the final name of the artifact before zipping. That way you do not have to rename the directory later.

2021-03-24 12:00 UTC, takev commented on .github/workflows/build-on-windows.yml
> +          $TRIPLET=$("${{ matrix.config.VCPKG_TARGET_TRIPLET }}".Replace("-windows",""))
I rather keep -windows as part of the artifact especially when we get -linux versions.

2021-03-24 17:11 UTC, jakoch commented
I wonder why the first push of this PR, went green on the tests for the PCH:ON build.
The logger [prints during tests](https://github.com/ttauri-project/ttauri/runs/2181808601#step:14:209), but the test run doesn't crash, it actually [passes](https://github.com/ttauri-project/ttauri/runs/2181808601#step:14:788).  

The changes regarding the folder structure? Executables are build, resources for tests are there.
Hmm.. maybe globbing fails due to `\version-0.3.0\`?

The only other change is  `Release` to `RelWithDebInfo`? Does this have an influence on the log level?

2021-03-25 16:39 UTC, takev approved these changes

2021-03-25 16:40 UTC, merged